language: java

jdk:
  - oraclejdk8

after_success:
- ./gradlew jacocoTestReport coveralls

env:
  global:
    - secure: "H+/ZmDVWAbSgUOWQcDYgrzIsihQN6IRbNiPqsIDdd4cChIIhnTkDAGXVn78y26scaapZxswB3pO91DxsyHXMI3z8GBOx2iSIvyCh9lPXZ918ChdFq0vvwZxq4PFYMxzyleLQ/fS1dRqiKCfT0F5gnrQgdz/yiEDcZvNnCEUwUrpjt+cBO9jm0pRhJxZFcN89qp7cq+NjxWOL9YLHGGHO0kGg1ta+fhVayCI9WaYc1rhG/uYEGMfLvGOz8uFNsF+w40Q3vdgFczQp1eyZvrpsxe1gh4Z7tHcenYbly05olCX1L8Q8Vqxa4TfHu/4dc+w3CNj55ZAGHavD+jCVsO70+ocCF3tbbs8siMHJYPDI29qT/+yfmM6siu4bg19HI+5cgtMoOjooFQTyey/2vKTI4KSKkKkfNgx+RJfd1M7JZbbsEf9ZGWoJ5hCkCNcKHi3gIvPiKe8RDt/+HsxGXGjlQKPQQSZrtFEONGCwWg+cx/1hVn1hDsadDDjjoCf7Tfs0p2bQt6KECWFA18Xfn4U8EzHPcQRDaxrq1kUNXhy6eXVARhHun8BhWCwyZ9Ww5rm26LoeUjeXpYTkm2ZCx4OMp9BTYdt2kvztLhKM5NLpeSGgTvxVkNdJIBtoP0PtvncEe5AB0Z9vcrpOQTI9qA3fShKYvYlH0nTeOGGcCmYCh7U="
