language: java

jdk:
  - oraclejdk8

before_install:
  - pip install --user codecov

after_success:
  - codecov

env:
  global:
    - secure: XapvTFpcb33knRgafmdm2cNDmFoDa0xDDohr0raCy3QJRVkQCjFkeFDNmeKet1eJYLPKSem98QoeIg5BZ3BJofcWmoxdm/I8J/ytsVSSIiSABZwSN6cbhdf9DWlTW3mbj4dw2YDcHqTlJUXKmD4eH9zLbXmPdV4ZQ3yBv7fMD9+AlRVS6b98NSFQY1VXSTGwchsHvco7l9GO6XYqOSEOiJC/clUSTQgC9ROMA1Y2/+9PfpX51QwScsEusUrw4V+7N0LyiHQn/z8Y1dGqNB8HirZIKGVl3BQwLtW1kV6KsrA3qsnBHdQ3p8uzSm9jmMJOZUaH0yf2v2s2U2Toknr9MBD4j49txPzXltcHdMBYzbYLa6V915Tcn3IfL+G5Fq+DhEcMo+NwaP7UQERrYiCxC+Nqd9uDndbbq0qC8Lwd8uthEBibros6qZv+JsQdfMcJX95v57RftVpvg+z+uEX6NMXujIQq1xwYi2P7/14F056mO5NQ+5+yx7LUgCQlS3RyKDuFKK8nQlVR060tUAyEGHZOmAvDebpCJCnaJNn3pFCnBLf00oedfnzYlDClJIHnCHIeiTnd2PYj3GZJ0lKb8Upv21lonc+87Rrclvul1Sonh0pMoy30U8LpapVTWAm47oJgY+pujtH+n/tWEGMG/XFCoi9HxPQU3ab73GAirK8=
    - secure: "B4FiXClWR1kr6GekLSzj8nfq/wT8AN5dUpwnTf/Rhw/+09PNhaAHi9/5kdK8h9v3k34zG3suuGV8WnT7nf8ksdtlmdxZXFgIzgoELlManN/sgtBAIXx3NchM1jtVsQlbbfpx1tAQu18EGNm5NnEGaZVB/uKBZqColgHSXQfPCB8useVNqgKsXJMvZkBS4hCb0R7oXXzerVoF/wFo63ultpQGHpaCzfXtTBiFxouO1GOE4tbg1aleRh8NEV+HLjASOZ7kgQgl+X/1ZSBE9RtdMBZ115s+Fqzj8ilEpVXLwRk5H572b09d4Rqv1Oi0of6HhVPkig1S5l0bOUnB0yRScnFlOJ6aaEH5aKW9o+jWbZ5ohr1TDk2/zC452mG1BUnXd+7DrunvQI4uTzWqv7XDszqJp+r8e45T/VBpFBMXiUsu1CAz7D86fvkOk0p/gfUclTzXOdLtvQco6jK9aGpwnico4f6G55MFmejVC8LIOHoenzSYOl39bYCrO27XNZwnjb5YGBsmbL6tNzYy5pjHr8Cr4OM8ZL+AMyEEeYhjJeLd9Y/GZ399sS/EqjZkEMf6pglgWPi2c0hQGvUrJNLq+HP2RjI3CbCOz7mzqEI0XiVZr5rwvYTsdhRy0HxeihSpkrZlT1c3mlwgdJ/QT/P/DvGawofn7P619WGQe7jh7N0="
